name: main-check

on: [push]

jobs:

    chek-test-lint-codeclimate:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-versions: ['8.2']
        steps:

            - uses: actions/checkout@v4
     
          
            - name: Set up PHP ${{ matrix.php-versions }}
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php-versions }}

            - name: setup app
              run: make setup

            - name: linter
              run: make lint

            - name: phpunit-tests
              run: make test

            - name: Run test & publish code coverage
              uses: paambaati/codeclimate-action@v5.0.0
              env:
                CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              with:
                coverageCommand: make test-coverage
                coverageLocations: ${{ github.workspace }}/build/logs/clover.xml:clover
                debug: true
            